LOCAL_PATH := jcrom/lge/mako

PRODUCT_PACKAGES += \
    Browser \
    Gallery2

PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/proprietary/system/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
	$(LOCAL_PATH)/proprietary/system/bin/bridgemgrd:system/bin/bridgemgrd \
	$(LOCAL_PATH)/proprietary/system/bin/btnvtool:system/bin/btnvtool \
	$(LOCAL_PATH)/proprietary/system/bin/diag_klog:system/bin/diag_klog \
	$(LOCAL_PATH)/proprietary/system/bin/diag_mdlog:system/bin/diag_mdlog \
	$(LOCAL_PATH)/proprietary/system/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
	$(LOCAL_PATH)/proprietary/system/bin/efsks:system/bin/efsks \
	$(LOCAL_PATH)/proprietary/system/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
	$(LOCAL_PATH)/proprietary/system/bin/ks:system/bin/ks \
	$(LOCAL_PATH)/proprietary/system/bin/mm-audio-send-cal:system/bin/mm-audio-send-cal \
	$(LOCAL_PATH)/proprietary/system/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
	$(LOCAL_PATH)/proprietary/system/bin/mpdecision:system/bin/mpdecision \
	$(LOCAL_PATH)/proprietary/system/bin/netmgrd:system/bin/netmgrd \
	$(LOCAL_PATH)/proprietary/system/bin/nl_listener:system/bin/nl_listener \
	$(LOCAL_PATH)/proprietary/system/bin/PktRspTest:system/bin/PktRspTest \
	$(LOCAL_PATH)/proprietary/system/bin/port-bridge:system/bin/port-bridge \
	$(LOCAL_PATH)/proprietary/system/bin/qcks:system/bin/qcks \
	$(LOCAL_PATH)/proprietary/system/bin/qmuxd:system/bin/qmuxd \
	$(LOCAL_PATH)/proprietary/system/bin/qseecomd:system/bin/qseecomd \
	$(LOCAL_PATH)/proprietary/system/bin/radish:system/bin/radish \
	$(LOCAL_PATH)/proprietary/system/bin/rmt_storage:system/bin/rmt_storage \
	$(LOCAL_PATH)/proprietary/system/bin/sensors.qcom:system/bin/sensors.qcom \
	$(LOCAL_PATH)/proprietary/system/bin/sns_cm_conc_test:system/bin/sns_cm_conc_test \
	$(LOCAL_PATH)/proprietary/system/bin/sns_cm_test:system/bin/sns_cm_test \
	$(LOCAL_PATH)/proprietary/system/bin/sns_debug_file_test:system/bin/sns_debug_file_test \
	$(LOCAL_PATH)/proprietary/system/bin/sns_dsps_tc0001:system/bin/sns_dsps_tc0001 \
	$(LOCAL_PATH)/proprietary/system/bin/sns_smr_loopback_test:system/bin/sns_smr_loopback_test \
	$(LOCAL_PATH)/proprietary/system/bin/test_diag:system/bin/test_diag \
	$(LOCAL_PATH)/proprietary/system/bin/thermald:system/bin/thermald \
	$(LOCAL_PATH)/proprietary/system/bin/usbhub:system/bin/usbhub \
	$(LOCAL_PATH)/proprietary/system/bin/usbhub_init:system/bin/usbhub_init \
	$(LOCAL_PATH)/proprietary/system/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
	$(LOCAL_PATH)/proprietary/system/etc/diag.cfg:system/etc/diag.cfg \
	$(LOCAL_PATH)/proprietary/system/etc/DxHDCP.cfg:system/etc/DxHDCP.cfg \
	$(LOCAL_PATH)/proprietary/system/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
	$(LOCAL_PATH)/proprietary/system/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
	$(LOCAL_PATH)/proprietary/system/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
	$(LOCAL_PATH)/proprietary/system/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
	$(LOCAL_PATH)/proprietary/system/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
	$(LOCAL_PATH)/proprietary/system/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
	$(LOCAL_PATH)/proprietary/system/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
	$(LOCAL_PATH)/proprietary/system/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
	$(LOCAL_PATH)/proprietary/system/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
	$(LOCAL_PATH)/proprietary/system/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
	$(LOCAL_PATH)/proprietary/system/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
	$(LOCAL_PATH)/proprietary/system/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
	$(LOCAL_PATH)/proprietary/system/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
	$(LOCAL_PATH)/proprietary/system/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
	$(LOCAL_PATH)/proprietary/system/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
	$(LOCAL_PATH)/proprietary/system/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
	$(LOCAL_PATH)/proprietary/system/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
	$(LOCAL_PATH)/proprietary/system/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
	$(LOCAL_PATH)/proprietary/system/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
	$(LOCAL_PATH)/proprietary/system/lib/egl/libplayback_adreno200.so:system/lib/egl/libplayback_adreno200.so \
	$(LOCAL_PATH)/proprietary/system/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
	$(LOCAL_PATH)/proprietary/system/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
	$(LOCAL_PATH)/proprietary/system/lib/libacdbloader.so:system/lib/libacdbloader.so \
	$(LOCAL_PATH)/proprietary/system/lib/libAKM.so:system/lib/libAKM.so \
	$(LOCAL_PATH)/proprietary/system/lib/libalsautils.so:system/lib/libalsautils.so \
	$(LOCAL_PATH)/proprietary/system/lib/libaudcal.so:system/lib/libaudcal.so \
	$(LOCAL_PATH)/proprietary/system/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
	$(LOCAL_PATH)/proprietary/system/lib/libaudioparsers.so:system/lib/libaudioparsers.so \
	$(LOCAL_PATH)/proprietary/system/lib/libC2D2.so:system/lib/libC2D2.so \
	$(LOCAL_PATH)/proprietary/system/lib/libc2d2_a3xx.so:system/lib/libc2d2_a3xx.so \
	$(LOCAL_PATH)/proprietary/system/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
	$(LOCAL_PATH)/proprietary/system/lib/libcamera_fast_af.so:system/lib/libcamera_fast_af.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_imx111_default_video.so:system/lib/libchromatix_imx111_default_video.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_imx111_preview.so:system/lib/libchromatix_imx111_preview.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_imx111_zsl.so:system/lib/libchromatix_imx111_zsl.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_imx119_default_video.so:system/lib/libchromatix_imx119_default_video.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_imx119_preview.so:system/lib/libchromatix_imx119_preview.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_mt9e013_video_hfr.so:system/lib/libchromatix_mt9e013_video_hfr.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_ov5647_default_video.so:system/lib/libchromatix_ov5647_default_video.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_ov5647_video_hfr.so:system/lib/libchromatix_ov5647_video_hfr.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_ov8825_default_video.so:system/lib/libchromatix_ov8825_default_video.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_ov8825_preview.so:system/lib/libchromatix_ov8825_preview.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_ov9726_default_video.so:system/lib/libchromatix_ov9726_default_video.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_ov9726_preview.so:system/lib/libchromatix_ov9726_preview.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_vx6953_default_video.so:system/lib/libchromatix_vx6953_default_video.so \
	$(LOCAL_PATH)/proprietary/system/lib/libchromatix_vx6953_preview.so:system/lib/libchromatix_vx6953_preview.so \
	$(LOCAL_PATH)/proprietary/system/lib/libCommandSvc.so:system/lib/libCommandSvc.so \
	$(LOCAL_PATH)/proprietary/system/lib/libconfigdb.so:system/lib/libconfigdb.so \
	$(LOCAL_PATH)/proprietary/system/lib/libcsd-client.so:system/lib/libcsd-client.so \
	$(LOCAL_PATH)/proprietary/system/lib/libdiag.so:system/lib/libdiag.so \
	$(LOCAL_PATH)/proprietary/system/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
	$(LOCAL_PATH)/proprietary/system/lib/libdrmfs.so:system/lib/libdrmfs.so \
	$(LOCAL_PATH)/proprietary/system/lib/libdrmtime.so:system/lib/libdrmtime.so \
	$(LOCAL_PATH)/proprietary/system/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
	$(LOCAL_PATH)/proprietary/system/lib/libdsprofile.so:system/lib/libdsprofile.so \
	$(LOCAL_PATH)/proprietary/system/lib/libdss.so:system/lib/libdss.so \
	$(LOCAL_PATH)/proprietary/system/lib/libdsucsd.so:system/lib/libdsucsd.so \
	$(LOCAL_PATH)/proprietary/system/lib/libdsutils.so:system/lib/libdsutils.so \
	$(LOCAL_PATH)/proprietary/system/lib/libDxHdcp.so:system/lib/libDxHdcp.so \
	$(LOCAL_PATH)/proprietary/system/lib/libgemini.so:system/lib/libgemini.so \
	$(LOCAL_PATH)/proprietary/system/lib/libgsl.so:system/lib/libgsl.so \
	$(LOCAL_PATH)/proprietary/system/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
	$(LOCAL_PATH)/proprietary/system/lib/libidl.so:system/lib/libidl.so \
	$(LOCAL_PATH)/proprietary/system/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
	$(LOCAL_PATH)/proprietary/system/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
	$(LOCAL_PATH)/proprietary/system/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
	$(LOCAL_PATH)/proprietary/system/lib/libllvm-a3xx.so:system/lib/libllvm-a3xx.so \
	$(LOCAL_PATH)/proprietary/system/lib/libllvm-arm.so:system/lib/libllvm-arm.so \
	$(LOCAL_PATH)/proprietary/system/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmercury.so:system/lib/libmercury.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmmipl.so:system/lib/libmmipl.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmmjps.so:system/lib/libmmjps.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmmmpo.so:system/lib/libmmmpo.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmmmpod.so:system/lib/libmmmpod.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
	$(LOCAL_PATH)/proprietary/system/lib/libmorpho_noise_reduction.so:system/lib/libmorpho_noise_reduction.so \
	$(LOCAL_PATH)/proprietary/system/lib/libnetmgr.so:system/lib/libnetmgr.so \
	$(LOCAL_PATH)/proprietary/system/lib/liboemcamera.so:system/lib/liboemcamera.so \
	$(LOCAL_PATH)/proprietary/system/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
	$(LOCAL_PATH)/proprietary/system/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
	$(LOCAL_PATH)/proprietary/system/lib/libOpenCL.so:system/lib/libOpenCL.so \
	$(LOCAL_PATH)/proprietary/system/lib/libOpenVG.so:system/lib/libOpenVG.so \
	$(LOCAL_PATH)/proprietary/system/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
	$(LOCAL_PATH)/proprietary/system/lib/libqdi.so:system/lib/libqdi.so \
	$(LOCAL_PATH)/proprietary/system/lib/libqdp.so:system/lib/libqdp.so \
	$(LOCAL_PATH)/proprietary/system/lib/libqmi.so:system/lib/libqmi.so \
	$(LOCAL_PATH)/proprietary/system/lib/libqmiservices.so:system/lib/libqmiservices.so \
	$(LOCAL_PATH)/proprietary/system/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
	$(LOCAL_PATH)/proprietary/system/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
	$(LOCAL_PATH)/proprietary/system/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
	$(LOCAL_PATH)/proprietary/system/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
	$(LOCAL_PATH)/proprietary/system/lib/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \
	$(LOCAL_PATH)/proprietary/system/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
	$(LOCAL_PATH)/proprietary/system/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
	$(LOCAL_PATH)/proprietary/system/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
	$(LOCAL_PATH)/proprietary/system/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
	$(LOCAL_PATH)/proprietary/system/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
	$(LOCAL_PATH)/proprietary/system/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
	$(LOCAL_PATH)/proprietary/system/lib/libsensor1.so:system/lib/libsensor1.so \
	$(LOCAL_PATH)/proprietary/system/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
	$(LOCAL_PATH)/proprietary/system/lib/libsensor_test.so:system/lib/libsensor_test.so \
	$(LOCAL_PATH)/proprietary/system/lib/libsensor_user_cal.so:system/lib/libsensor_user_cal.so \
	$(LOCAL_PATH)/proprietary/system/lib/libstagefright_hdcp.so:system/lib/libstagefright_hdcp.so \
	$(LOCAL_PATH)/proprietary/system/lib/libxml.so:system/lib/libxml.so \
	$(LOCAL_PATH)/proprietary/system/lib/lib_dlb_msd.so:system/lib/lib_dlb_msd.so \
	$(LOCAL_PATH)/proprietary/system/vendor/firmware/bcm2079x_firmware.ncd:system/vendor/firmware/bcm2079x_firmware.ncd \
	$(LOCAL_PATH)/proprietary/system/vendor/firmware/bcm2079x_pre_firmware.ncd:system/vendor/firmware/bcm2079x_pre_firmware.ncd \
	$(LOCAL_PATH)/proprietary/system/vendor/firmware/discretix/dxhdcp2.b00:system/vendor/firmware/discretix/dxhdcp2.b00 \
	$(LOCAL_PATH)/proprietary/system/vendor/firmware/discretix/dxhdcp2.b01:system/vendor/firmware/discretix/dxhdcp2.b01 \
	$(LOCAL_PATH)/proprietary/system/vendor/firmware/discretix/dxhdcp2.b02:system/vendor/firmware/discretix/dxhdcp2.b02 \
	$(LOCAL_PATH)/proprietary/system/vendor/firmware/discretix/dxhdcp2.b03:system/vendor/firmware/discretix/dxhdcp2.b03 \
	$(LOCAL_PATH)/proprietary/system/vendor/firmware/discretix/dxhdcp2.mdt:system/vendor/firmware/discretix/dxhdcp2.mdt \
	$(LOCAL_PATH)/proprietary/system/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
	$(LOCAL_PATH)/proprietary/system/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
	$(LOCAL_PATH)/proprietary/system/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
	$(LOCAL_PATH)/proprietary/system/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
	$(LOCAL_PATH)/proprietary/system/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
	$(LOCAL_PATH)/proprietary/system/media/video/AndroidInSpace.240p.mp4:system/media/video/AndroidInSpace.240p.mp4 \
	$(LOCAL_PATH)/proprietary/system/media/video/AndroidInSpace.480p.mp4:system/media/video/AndroidInSpace.480p.mp4 \
	$(LOCAL_PATH)/proprietary/system/media/video/Sunset.240p.mp4:system/media/video/Sunset.240p.mp4 \
	$(LOCAL_PATH)/proprietary/system/media/video/Sunset.480p.mp4:system/media/video/Sunset.480p.mp4 \
	$(LOCAL_PATH)/proprietary/system/media/LMprec_508.emd:system/media/LMprec_508.emd \
	$(LOCAL_PATH)/proprietary/system/media/PFFprec_600.emd:system/media/PFFprec_600.emd \
	$(LOCAL_PATH)/proprietary/system/media/bootanimation.zip:system/media/bootanimation.zip \
	$(LOCAL_PATH)/proprietary/wcd9310_anc.bin:system/etc/firmware/wcd9310/wcd9310_anc.bin \
	$(LOCAL_PATH)/proprietary/wcd9310_mbhc.bin:system/etc/firmware/wcd9310/wcd9310_mbhc.bin \
	$(LOCAL_PATH)/proprietary/system/lib/libjni_mosaic.so:system/lib/libjni_mosaic.so \
	$(LOCAL_PATH)/proprietary/system/lib/liblightcycle.so:system/lib/liblightcycle.so

$(call inherit-product-if-exists, frameworks/base/data/sounds/AudioPackage10.mk)

